import { Integration, SyncEvent } from "./types";

export const MOCK_INTEGRATIONS: Integration[] = [
  {
    id: "zeek",
    name: "Zeek Network Intrusion Sensor",
    category: "Security Sensors",
    status: "Connected",
    lastSync: "Just Now",
    dataType: "conn.log, http.log, dns.log",
    health: "Healthy",
    description: "Deep packet analyzer monitoring and parsing live raw network stream traces continuously at flow boundaries.",
    connectedServices: ["Filebeat"],
  },
  {
    id: "suricata",
    name: "Suricata Signature IDS",
    category: "Security Sensors",
    status: "Connected",
    lastSync: "Just Now",
    dataType: "eve.json, alerts",
    health: "Healthy",
    description: "Signature-based alert generation engine mapping real-time matching threat signatures or anomalies.",
    connectedServices: ["Filebeat"],
  },
  {
    id: "filebeat",
    name: "Filebeat Log Forwarder",
    category: "Security Sensors",
    status: "Connected",
    lastSync: "10s ago",
    dataType: "forwarding active",
    health: "Healthy",
    description: "High-performance shipping agent forwarding parsed telemetry logs directly into centralized message pools.",
    connectedServices: ["AWS SQS"],
  },
  {
    id: "aws-sqs",
    name: "AWS SQS Ingestion Queue",
    category: "Messaging",
    status: "Connected",
    lastSync: "Just Now",
    dataType: "Buffered queue packets",
    health: "Healthy",
    region: "ap-southeast-1",
    description: "Asynchronous transit point buffering massive raw telemetry payloads between sensor forwarders and the core system.",
    connectedServices: ["Security Analytics Engine"],
  },
  {
    id: "aws-s3",
    name: "AWS S3 Cold Storage Archive",
    category: "Storage",
    status: "Connected",
    lastSync: "2m ago",
    dataType: "Historical pcap, raw logs JSON",
    health: "Healthy",
    region: "ap-southeast-1",
    description: "Durable, encrypted long-term backup and audit data lake storage for all security datasets.",
    connectedServices: ["AWS Lifecycle Policy"],
  },
  {
    id: "aws-rds",
    name: "AWS RDS PostgreSQL Platform Database",
    category: "Database",
    status: "Connected",
    lastSync: "Just Now",
    dataType: "Consolidated alerts, asset directories, config tables",
    health: "Healthy",
    region: "ap-southeast-1",
    description: "Authoritative relational database housing metadata matching security events, alerts index, and synchronization sessions.",
    connectedServices: ["Security Analytics Engine", "WebSocket Dispatcher"],
  },
  {
    id: "aws-cloudwatch",
    name: "AWS CloudWatch Auditor",
    category: "Cloud Services",
    status: "Connected",
    lastSync: "5m ago",
    dataType: "Cloud resource audit logs, CPU metrics",
    health: "Healthy",
    region: "ap-southeast-1",
    description: "AWS cloud boundary log collector auditing platform resources performance and API invocation patterns.",
    connectedServices: ["AWS IAM Auditor"],
  },
];

export const MOCK_SYNC_EVENTS: SyncEvent[] = [
  {
    id: "e1",
    timestamp: "JUST NOW",
    integration: "Zeek Network Intrusion Sensor",
    event: "conn.log flow ingest synchronization completed",
    status: "Success",
  },
  {
    id: "e2",
    timestamp: "JUST NOW",
    integration: "Suricata Signature IDS",
    event: "eve.json signature stream connection active",
    status: "Active",
  },
  {
    id: "e3",
    timestamp: "45S AGO",
    integration: "AWS SQS Ingestion Queue",
    event: "FIFO Buffer connection successfully verified and synchronized",
    status: "Success",
  },
  {
    id: "e4",
    timestamp: "1M AGO",
    integration: "AWS RDS PostgreSQL Platform Database",
    event: "Relational persistence vacuum and audit storage sync complete",
    status: "Success",
  },
  {
    id: "e5",
    timestamp: "2M AGO",
    integration: "Filebeat Log Forwarder",
    event: "Log forwarding sequence synchronized with remote buffer",
    status: "Success",
  },
  {
    id: "e6",
    timestamp: "5M AGO",
    integration: "AWS S3 Cold Storage Archive",
    event: "Raw historical telemetry dump sync completed successfully",
    status: "Success",
  },
  {
    id: "e7",
    timestamp: "8M AGO",
    integration: "AWS CloudWatch Auditor",
    event: "Infrastructure metric logging stream synchronized",
    status: "Success",
  },
];
