export type AppView =
  | "dashboard"
  | "alerts"
  | "network"
  | "endpoints"
  | "integrations"
  | "playbooks"
  | "reports"
  | "settings"
  | "cloud"
  | "ai-threat-detection"
  | "attack-surface"
  | "mitre-attack"
  | "case-management"
  | "threat-intel";
