export type AppView =
  | "dashboard"
  | "alerts"
  | "network"
  | "endpoints"
  | "cloud"
  | "threat-intel"
  | "integrations"
  | "playbooks"
  | "reports"
  | "settings"
  | "ai-threat-detection"
  | "attack-surface"
  | "mitre-attack"
  | "case-management";
