import { SettingsStateData } from "./settingsConfig";

export const DEFAULT_COMPLETE_SETTINGS: SettingsStateData = {
  systemName: "Hybrid SOC - Zeek & AI Fusion",
  version: "v3.0",
  environment: "Development",
  timezone: "UTC+7",
  language: "English",

  theme: "Dark",
  density: "Comfortable",
  sidebarMode: "Expanded",
  animations: "Enable",
  colorBlindMode: false,
  severityPreview: "Critical",

  ai1Status: "Loaded",
  ai1Model: "Isolation Forest",
  ai1Version: "1.0",
  ai1Threshold: 0.65,
  ai2aStatus: "Loaded",
  ai2aModel: "XGBoost",
  ai2aClasses: ["Normal", "Port Scan", "DoS", "Brute Force", "Botnet"],
  ai2aConfidence: 75,
  ai2bStatus: "Loaded",
  ai2bModel: "XGBoost",
  ai2bThreshold: 82,
  ai2bAttackTypes: ["XSS", "SQLi", "Command Injection", "Path Traversal"],
  batchSize: 50,
  inferenceMode: "Realtime",

  weightAI1: 20,
  weightAI2A: 35,
  weightAI2B: 35,
  weightSuricata: 10,
  thresholdLow: 40,
  thresholdMedium: 70,
  thresholdHigh: 90,
  thresholdCritical: 100,

  alertColors: {
    Critical: "#ef4444",
    High: "#f97316",
    Medium: "#eab308",
    Low: "#ef4444" // Default Low
  },
  alertSounds: { Critical: true, High: true, Medium: false, Low: false },
  alertNotifications: { Critical: true, High: true, Medium: true, Low: false },
  alertRetention: "30 Days",
  alertAutoClose: true,
  alertAutoCloseDuration: "6h",

  awsSqsUrl: "https://sqs.us-east-1.amazonaws.com/123456789012/soc-zeek-queue.fifo",
  awsSqsStatus: "Connected",
  awsSqsMessages: 245,
  awsS3Bucket: "soc-log-storage",
  awsS3Status: "Connected",
  awsRdsDatabase: "PostgreSQL",
  awsRdsStatus: "Connected",
  awsCloudWatchStatus: "Connected",

  zeekStatus: "Connected",
  zeekLogs: ["conn.log", "http.log"],
  suricataStatus: "Connected",
  suricataRules: 2345,
  filebeatStatus: "Connected",
  websocketStatus: "Connected",
  websocketLatency: 15,

  connDatasetName: "conn_train_v3.csv (50,000 flows)",
  httpDatasetName: "http_train_v3.csv (25,000 flows)",
  datasetDuplicates: 1.2,
  datasetMissing: 0.5,
  datasetPsi: 0.08,
  datasetOutliers: 1.4,
  datasetMismatchStatus: "Safe",
  datasetLab: "Lab-Simulation-Zeekv3",
  datasetPublic: "CSE-CIC-IDS2018",

  reportFormat: "PDF",
  reportSchedule: "Weekly",
  reportAutoGenerate: true,

  users: [
    { id: 1, username: "phutd@security.net", role: "Admin", status: "Active", lastLogin: "2026-06-05 08:34:12" },
    { id: 2, username: "analyst_alpha@soc.net", role: "SOC Analyst", status: "Active", lastLogin: "2026-06-05 09:12:44" },
    { id: 3, username: "engineer_prime@soc.net", role: "Security Engineer", status: "Active", lastLogin: "2026-06-05 07:02:11" },
    { id: 4, username: "viewer_standard@soc.net", role: "Viewer", status: "Active", lastLogin: "2026-06-04 15:44:02" },
  ],
  permissions: {
    Dashboard: { Admin: true, "SOC Analyst": true, "Security Engineer": true, Viewer: true },
    Alerts: { Admin: true, "SOC Analyst": true, "Security Engineer": true, Viewer: false },
    Reports: { Admin: true, "SOC Analyst": true, "Security Engineer": false, Viewer: false },
    Settings: { Admin: true, "SOC Analyst": false, "Security Engineer": true, Viewer: false },
    Users: { Admin: true, "SOC Analyst": false, "Security Engineer": false, Viewer: false },
  },

  // 11. Monitoring Defaults
  cpuUsage: 38,
  ramUsage: 54,
  diskUsage: 42,
  aiEngineHealth: {
    ai1: true,
    ai2a: true,
    ai2b: true,
    fusion: true,
  },
  connectedClients: 4,
  sqsQueueLength: 245,
  sqsProcessingRate: 1424,

  developerMode: true,
  debugConsole: true,
};
